"""add hashed_password to users

Revision ID: 9a9611e31c70
Revises: 0002
Create Date: 2026-07-01 23:03:52.719497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a9611e31c70'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_index('ix_conversations_scenario_id', table_name='conversations')
    op.drop_index('ix_conversations_user_id', table_name='conversations')
    op.drop_column('conversations', 'ended_at')
    op.drop_column('conversations', 'niveau_cecrl')
    op.drop_column('conversations', 'started_at')
    op.add_column('corrections', sa.Column('erreur', sa.String(), nullable=False))
    op.add_column('corrections', sa.Column('correction', sa.String(), nullable=False))
    op.add_column('corrections', sa.Column('categorie', sa.String(), nullable=True))
    op.alter_column('corrections', 'explication',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('ix_corrections_message_id', table_name='corrections')
    op.create_unique_constraint(None, 'corrections', ['message_id'])
    op.drop_column('corrections', 'created_at')
    op.drop_column('corrections', 'erreur_originale')
    op.drop_column('corrections', 'type_erreur')
    op.drop_column('corrections', 'texte_corrige')
    op.add_column('exercises', sa.Column('categorie', sa.String(), nullable=True))
    op.add_column('exercises', sa.Column('question', sa.String(), nullable=False))
    op.add_column('exercises', sa.Column('reponse_attendue', sa.String(), nullable=False))
    op.alter_column('exercises', 'niveau_cecrl',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'A1'::character varying"))
    op.drop_index('ix_exercises_scenario_id', table_name='exercises')
    op.drop_constraint('exercises_scenario_id_fkey', 'exercises', type_='foreignkey')
    op.drop_column('exercises', 'created_at')
    op.drop_column('exercises', 'scenario_id')
    op.drop_column('exercises', 'contenu')
    op.drop_column('exercises', 'type_exercice')
    op.add_column('messages', sa.Column('contenu', sa.String(), nullable=False))
    op.drop_index('ix_messages_conversation_id', table_name='messages')
    op.drop_column('messages', 'content')
    op.drop_column('messages', 'audio_url')
    op.add_column('progress', sa.Column('niveau_estime', sa.String(), nullable=True))
    op.alter_column('progress', 'erreurs_frequentes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('ix_progress_user_id', table_name='progress')
    op.drop_column('progress', 'total_corrections')
    op.drop_column('progress', 'total_messages')
    op.drop_column('progress', 'niveau_actuel')
    op.add_column('scenarios', sa.Column('contexte_prompt', sa.String(), nullable=True))
    op.alter_column('scenarios', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('scenarios', 'created_at')
    op.drop_column('scenarios', 'contexte')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('scenarios', sa.Column('contexte', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('scenarios', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.alter_column('scenarios', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('scenarios', 'contexte_prompt')
    op.add_column('progress', sa.Column('niveau_actuel', sa.VARCHAR(), server_default=sa.text("'A1'::character varying"), autoincrement=False, nullable=True))
    op.add_column('progress', sa.Column('total_messages', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('progress', sa.Column('total_corrections', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.create_index('ix_progress_user_id', 'progress', ['user_id'], unique=True)
    op.alter_column('progress', 'erreurs_frequentes',
               existing_type=sa.String(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('progress', 'niveau_estime')
    op.add_column('messages', sa.Column('audio_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_index('ix_messages_conversation_id', 'messages', ['conversation_id'], unique=False)
    op.drop_column('messages', 'contenu')
    op.add_column('exercises', sa.Column('type_exercice', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('exercises', sa.Column('contenu', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('exercises', sa.Column('scenario_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('exercises', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_foreign_key('exercises_scenario_id_fkey', 'exercises', 'scenarios', ['scenario_id'], ['id'])
    op.create_index('ix_exercises_scenario_id', 'exercises', ['scenario_id'], unique=False)
    op.alter_column('exercises', 'niveau_cecrl',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'A1'::character varying"))
    op.drop_column('exercises', 'reponse_attendue')
    op.drop_column('exercises', 'question')
    op.drop_column('exercises', 'categorie')
    op.add_column('corrections', sa.Column('texte_corrige', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('corrections', sa.Column('type_erreur', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('corrections', sa.Column('erreur_originale', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('corrections', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'corrections', type_='unique')
    op.create_index('ix_corrections_message_id', 'corrections', ['message_id'], unique=False)
    op.alter_column('corrections', 'explication',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('corrections', 'categorie')
    op.drop_column('corrections', 'correction')
    op.drop_column('corrections', 'erreur')
    op.add_column('conversations', sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('conversations', sa.Column('niveau_cecrl', sa.VARCHAR(), server_default=sa.text("'A1'::character varying"), autoincrement=False, nullable=True))
    op.add_column('conversations', sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index('ix_conversations_user_id', 'conversations', ['user_id'], unique=False)
    op.create_index('ix_conversations_scenario_id', 'conversations', ['scenario_id'], unique=False)
    op.drop_column('conversations', 'created_at')
    # ### end Alembic commands ###
